<?php
// database/seeders/AgendaSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Agenda;
use App\Models\Admin;
use Carbon\Carbon;
use Illuminate\Support\Str;

class AgendaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get first admin user for created_by
        $admin = Admin::first();
        $adminId = $admin ? $admin->id : null;

        $agenda = [
            [
                'judul' => 'Rapat Koordinasi Bulanan RT/RW',
                'slug' => 'rapat-koordinasi-bulanan-rt-rw',
                'deskripsi' => 'Rapat koordinasi rutin bulanan untuk membahas program kerja dan evaluasi kegiatan RT/RW di Desa Papanloe.',
                'detail' => '<p>Rapat koordinasi bulanan RT/RW merupakan forum komunikasi dan koordinasi antara perangkat desa dengan para ketua RT dan RW untuk membahas berbagai hal terkait pembangunan dan pelayanan kepada masyarakat.</p><p><strong>Agenda Pembahasan:</strong></p><ul><li>Evaluasi program bulan sebelumnya</li><li>Rencana kegiatan bulan mendatang</li><li>Permasalahan yang dihadapi masyarakat</li><li>Koordinasi program pembangunan</li><li>Rencana anggaran kegiatan</li></ul>',
                'kategori' => 'rapat',
                'status' => 'aktif',
                'prioritas' => 'tinggi',
                'tanggal_mulai' => Carbon::now()->addDays(5)->setTime(9, 0),
                'tanggal_selesai' => Carbon::now()->addDays(5)->setTime(12, 0),
                'waktu_mulai' => '09:00',
                'waktu_selesai' => '12:00',
                'tempat' => 'Balai Desa Papanloe',
                'alamat_lengkap' => 'Jl. Poros Desa Papanloe, Kec. Somba Opu, Kab. Gowa',
                'penyelenggara' => 'Pemerintah Desa Papanloe',
                'target_peserta' => 'Ketua RT, Ketua RW, Perangkat Desa',
                'kapasitas_peserta' => 50,
                'perlu_pendaftaran' => false,
                'contact_person' => 'Sekretaris Desa',
                'contact_phone' => '081234567890',
                'contact_email' => 'sekdes@papanloe.desa.id',
                'persyaratan' => 'Ketua RT/RW aktif, membawa laporan kegiatan',
                'fasilitas' => 'Konsumsi, ATK, Ruang ber-AC',
                'catatan' => 'Mohon hadir tepat waktu dan membawa laporan kegiatan masing-masing wilayah.',
                'meta_description' => 'Rapat koordinasi bulanan RT/RW Desa Papanloe untuk membahas program kerja dan evaluasi kegiatan.',
                'views' => rand(50, 200),
                'is_featured' => true,
                'created_by' => $adminId,
                'updated_by' => $adminId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Gotong Royong Pembersihan Lingkungan',
                'slug' => 'gotong-royong-pembersihan-lingkungan',
                'deskripsi' => 'Kegiatan gotong royong pembersihan lingkungan serentak di seluruh wilayah Desa Papanloe dalam rangka menjaga kebersihan dan kesehatan lingkungan.',
                'detail' => '<p>Kegiatan gotong royong pembersihan lingkungan merupakan kegiatan rutin yang dilaksanakan setiap bulan untuk menjaga kebersihan dan kesehatan lingkungan di Desa Papanloe.</p><p><strong>Kegiatan yang dilakukan:</strong></p><ul><li>Pembersihan jalan dan got</li><li>Pembersihan tempat ibadah</li><li>Pembersihan fasilitas umum</li><li>Penanaman pohon</li><li>Sosialisasi hidup bersih dan sehat</li></ul>',
                'kategori' => 'gotong_royong',
                'status' => 'aktif',
                'prioritas' => 'normal',
                'tanggal_mulai' => Carbon::now()->addDays(12)->setTime(7, 0),
                'tanggal_selesai' => Carbon::now()->addDays(12)->setTime(10, 0),
                'waktu_mulai' => '07:00',
                'waktu_selesai' => '10:00',
                'tempat' => 'Seluruh Wilayah Desa Papanloe',
                'alamat_lengkap' => 'Berkumpul di Balai Desa kemudian menyebar ke seluruh wilayah',
                'penyelenggara' => 'Pemerintah Desa Papanloe',
                'target_peserta' => 'Seluruh masyarakat Desa Papanloe',
                'perlu_pendaftaran' => false,
                'contact_person' => 'Kaur Pembangunan',
                'contact_phone' => '081234567891',
                'persyaratan' => 'Membawa alat kebersihan sendiri',
                'fasilitas' => 'Konsumsi, Alat kebersihan tambahan, P3K',
                'catatan' => 'Mari bersama-sama menjaga kebersihan lingkungan desa kita tercinta.',
                'meta_description' => 'Kegiatan gotong royong pembersihan lingkungan serentak di Desa Papanloe untuk menjaga kebersihan dan kesehatan.',
                'views' => rand(100, 300),
                'is_featured' => true,
                'created_by' => $adminId,
                'updated_by' => $adminId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Sosialisasi Program Bantuan Sosial 2025',
                'slug' => 'sosialisasi-program-bantuan-sosial-2025',
                'deskripsi' => 'Sosialisasi program bantuan sosial tahun 2025 untuk memberikan informasi kepada masyarakat tentang syarat dan mekanisme penerimaan bantuan.',
                'detail' => '<p>Sosialisasi program bantuan sosial tahun 2025 bertujuan untuk memberikan informasi yang jelas dan transparan kepada masyarakat mengenai berbagai program bantuan yang tersedia.</p><p><strong>Program yang disosialisasikan:</strong></p><ul><li>Bantuan Langsung Tunai (BLT)</li><li>Program Keluarga Harapan (PKH)</li><li>Bantuan Pangan Non Tunai (BPNT)</li><li>Bantuan Stimulan Perumahan Swadaya (BSPS)</li><li>Program Indonesia Pintar (PIP)</li></ul>',
                'kategori' => 'sosialisasi',
                'status' => 'aktif',
                'prioritas' => 'tinggi',
                'tanggal_mulai' => Carbon::now()->addDays(20)->setTime(14, 0),
                'tanggal_selesai' => Carbon::now()->addDays(20)->setTime(16, 0),
                'waktu_mulai' => '14:00',
                'waktu_selesai' => '16:00',
                'tempat' => 'Aula Balai Desa Papanloe',
                'alamat_lengkap' => 'Jl. Poros Desa Papanloe, Kec. Somba Opu, Kab. Gowa',
                'penyelenggara' => 'Dinas Sosial Kab. Gowa & Pemerintah Desa Papanloe',
                'target_peserta' => 'Masyarakat Desa Papanloe, khususnya calon penerima bantuan',
                'kapasitas_peserta' => 200,
                'perlu_pendaftaran' => true,
                'batas_pendaftaran' => Carbon::now()->addDays(18)->setTime(17, 0),
                'contact_person' => 'Kasi Kesejahteraan',
                'contact_phone' => '081234567892',
                'contact_email' => 'kesra@papanloe.desa.id',
                'persyaratan' => 'KTP, KK, Bukti penghasilan',
                'fasilitas' => 'Konsumsi, Materi sosialisasi, Door prize',
                'catatan' => 'Diharapkan masyarakat yang memenuhi syarat untuk hadir dan membawa dokumen yang diperlukan.',
                'meta_description' => 'Sosialisasi program bantuan sosial 2025 di Desa Papanloe untuk memberikan informasi syarat dan mekanisme bantuan.',
                'views' => rand(150, 400),
                'is_featured' => true,
                'created_by' => $adminId,
                'updated_by' => $adminId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Pelatihan Kewirausahaan untuk Pemuda',
                'slug' => 'pelatihan-kewirausahaan-untuk-pemuda',
                'deskripsi' => 'Pelatihan kewirausahaan untuk pemuda Desa Papanloe dalam rangka meningkatkan keterampilan dan membuka peluang usaha baru.',
                'detail' => '<p>Pelatihan kewirausahaan ini bertujuan untuk membekali pemuda Desa Papanloe dengan pengetahuan dan keterampilan dalam berwirausaha agar dapat menciptakan lapangan kerja dan meningkatkan perekonomian desa.</p><p><strong>Materi pelatihan:</strong></p><ul><li>Dasar-dasar kewirausahaan</li><li>Identifikasi peluang usaha</li><li>Penyusunan business plan</li><li>Manajemen keuangan usaha</li><li>Digital marketing</li><li>Akses permodalan</li></ul>',
                'kategori' => 'pelatihan',
                'status' => 'aktif',
                'prioritas' => 'normal',
                'tanggal_mulai' => Carbon::now()->addDays(25)->setTime(8, 0),
                'tanggal_selesai' => Carbon::now()->addDays(27)->setTime(16, 0),
                'waktu_mulai' => '08:00',
                'waktu_selesai' => '16:00',
                'tempat' => 'Balai Desa Papanloe',
                'alamat_lengkap' => 'Jl. Poros Desa Papanloe, Kec. Somba Opu, Kab. Gowa',
                'penyelenggara' => 'BUMDes Papanloe Maju & Karang Taruna',
                'target_peserta' => 'Pemuda usia 18-35 tahun',
                'kapasitas_peserta' => 30,
                'perlu_pendaftaran' => true,
                'batas_pendaftaran' => Carbon::now()->addDays(22)->setTime(17, 0),
                'contact_person' => 'Ketua Karang Taruna',
                'contact_phone' => '081234567893',
                'contact_email' => 'karangtaruna@papanloe.desa.id',
                'persyaratan' => 'Usia 18-35 tahun, KTP Desa Papanloe, Surat keterangan sehat',
                'fasilitas' => 'Konsumsi, Materi pelatihan, Sertifikat, Starter kit usaha',
                'biaya' => 0,
                'catatan' => 'Peserta yang lulus akan mendapat bantuan modal usaha dari BUMDes.',
                'meta_description' => 'Pelatihan kewirausahaan gratis untuk pemuda Desa Papanloe dengan bantuan modal usaha.',
                'views' => rand(80, 250),
                'is_featured' => false,
                'created_by' => $adminId,
                'updated_by' => $adminId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Upacara Peringatan HUT RI ke-80',
                'slug' => 'upacara-peringatan-hut-ri-ke-80',
                'deskripsi' => 'Upacara peringatan Hari Ulang Tahun Kemerdekaan Republik Indonesia ke-80 di Desa Papanloe dengan berbagai lomba dan kegiatan menarik.',
                'detail' => '<p>Peringatan HUT RI ke-80 akan dirayakan dengan meriah di Desa Papanloe. Acara ini merupakan momentum untuk mengenang jasa para pahlawan dan mempererat persatuan warga desa.</p><p><strong>Rangkaian acara:</strong></p><ul><li>Upacara bendera pagi hari</li><li>Lomba-lomba tradisional</li><li>Pentas seni budaya</li><li>Bazar kuliner khas daerah</li><li>Perlombaan olahraga</li><li>Hiburan musik dangdut</li></ul>',
                'kategori' => 'upacara',
                'status' => 'aktif',
                'prioritas' => 'tinggi',
                'tanggal_mulai' => Carbon::create(2025, 8, 17, 7, 0),
                'tanggal_selesai' => Carbon::create(2025, 8, 17, 21, 0),
                'waktu_mulai' => '07:00',
                'waktu_selesai' => '21:00',
                'tempat' => 'Lapangan Desa Papanloe',
                'alamat_lengkap' => 'Lapangan Desa Papanloe, Kec. Somba Opu, Kab. Gowa',
                'penyelenggara' => 'Pemerintah Desa Papanloe',
                'target_peserta' => 'Seluruh masyarakat Desa Papanloe',
                'perlu_pendaftaran' => false,
                'contact_person' => 'Panitia HUT RI',
                'contact_phone' => '081234567894',
                'persyaratan' => 'Memakai pakaian merah putih',
                'fasilitas' => 'Sound system, Panggung, Hadiah lomba, Konsumsi',
                'catatan' => 'Mari rayakan kemerdekaan dengan penuh semangat dan kebersamaan!',
                'meta_description' => 'Peringatan HUT RI ke-80 di Desa Papanloe dengan upacara, lomba, dan hiburan menarik.',
                'views' => rand(200, 500),
                'is_featured' => true,
                'created_by' => $adminId,
                'updated_by' => $adminId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kegiatan Posyandu Balita dan Lansia',
                'slug' => 'kegiatan-posyandu-balita-dan-lansia',
                'deskripsi' => 'Kegiatan Posyandu rutin bulanan untuk pemeriksaan kesehatan balita dan lansia serta pemberian vitamin dan imunisasi.',
                'detail' => '<p>Posyandu merupakan kegiatan rutin bulanan yang sangat penting untuk memantau kesehatan balita dan lansia di Desa Papanloe. Kegiatan ini dilaksanakan oleh kader kesehatan dengan didampingi tenaga medis dari Puskesmas.</p><p><strong>Layanan yang tersedia:</strong></p><ul><li>Penimbangan dan pengukuran balita</li><li>Pemeriksaan kesehatan lansia</li><li>Pemberian vitamin A</li><li>Imunisasi lengkap</li><li>Konsultasi gizi</li><li>Penyuluhan kesehatan</li></ul>',
                'kategori' => 'kegiatan',
                'status' => 'aktif',
                'prioritas' => 'normal',
                'tanggal_mulai' => Carbon::now()->addDays(30)->setTime(8, 0),
                'tanggal_selesai' => Carbon::now()->addDays(30)->setTime(12, 0),
                'waktu_mulai' => '08:00',
                'waktu_selesai' => '12:00',
                'tempat' => 'Balai RW 01 Desa Papanloe',
                'alamat_lengkap' => 'Balai RW 01, Dusun Papanloe Tengah',
                'penyelenggara' => 'Kader Posyandu & Puskesmas Somba Opu',
                'target_peserta' => 'Balita 0-5 tahun dan Lansia 60+ tahun',
                'perlu_pendaftaran' => false,
                'contact_person' => 'Ketua Kader Posyandu',
                'contact_phone' => '081234567895',
                'persyaratan' => 'Membawa KMS/buku kesehatan, KTP/KK',
                'fasilitas' => 'Pemeriksaan gratis, Vitamin, Makanan tambahan',
                'catatan' => 'Kegiatan ini rutin dilaksanakan setiap bulan untuk menjaga kesehatan keluarga.',
                'meta_description' => 'Posyandu bulanan Desa Papanloe untuk pemeriksaan kesehatan balita dan lansia gratis.',
                'views' => rand(60, 180),
                'is_featured' => false,
                'created_by' => $adminId,
                'updated_by' => $adminId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Musyawarah Desa Penyusunan RKPDesa 2026',
                'slug' => 'musyawarah-desa-penyusunan-rkpdesa-2026',
                'deskripsi' => 'Musyawarah Desa untuk penyusunan Rencana Kerja Pemerintah Desa (RKPDesa) tahun 2026 dengan melibatkan seluruh elemen masyarakat.',
                'detail' => '<p>Musyawarah Desa merupakan forum tertinggi dalam pengambilan keputusan di tingkat desa. Musdes kali ini akan membahas penyusunan RKPDesa 2026 yang akan menjadi acuan pembangunan desa selama satu tahun ke depan.</p><p><strong>Agenda pembahasan:</strong></p><ul><li>Evaluasi pelaksanaan RKPDesa 2025</li><li>Identifikasi kebutuhan pembangunan 2026</li><li>Prioritas program dan kegiatan</li><li>Alokasi anggaran per bidang</li><li>Mekanisme pelaksanaan kegiatan</li><li>Penetapan RKPDesa 2026</li></ul>',
                'kategori' => 'rapat',
                'status' => 'aktif',
                'prioritas' => 'urgent',
                'tanggal_mulai' => Carbon::now()->addDays(35)->setTime(9, 0),
                'tanggal_selesai' => Carbon::now()->addDays(35)->setTime(15, 0),
                'waktu_mulai' => '09:00',
                'waktu_selesai' => '15:00',
                'tempat' => 'Aula Balai Desa Papanloe',
                'alamat_lengkap' => 'Jl. Poros Desa Papanloe, Kec. Somba Opu, Kab. Gowa',
                'penyelenggara' => 'Pemerintah Desa Papanloe',
                'target_peserta' => 'BPD, Perangkat Desa, Tokoh Masyarakat, Ketua RT/RW, Perwakilan Organisasi',
                'kapasitas_peserta' => 100,
                'perlu_pendaftaran' => true,
                'batas_pendaftaran' => Carbon::now()->addDays(32)->setTime(17, 0),
                'contact_person' => 'Sekretaris Desa',
                'contact_phone' => '081234567896',
                'contact_email' => 'sekdes@papanloe.desa.id',
                'persyaratan' => 'Undangan resmi, KTP, Surat tugas (jika mewakili organisasi)',
                'fasilitas' => 'Konsumsi, ATK, Materi Musdes, Ruang ber-AC',
                'catatan' => 'Kehadiran sangat penting untuk menentukan arah pembangunan desa tahun 2026.',
                'meta_description' => 'Musyawarah Desa penyusunan RKPDesa 2026 Papanloe untuk menentukan program pembangunan tahun depan.',
                'views' => rand(40, 120),
                'is_featured' => false,
                'created_by' => $adminId,
                'updated_by' => $adminId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Festival Budaya dan Kuliner Desa Papanloe',
                'slug' => 'festival-budaya-dan-kuliner-desa-papanloe',
                'deskripsi' => 'Festival tahunan untuk memperkenalkan budaya lokal dan kuliner khas Desa Papanloe kepada masyarakat luas dan wisatawan.',
                'detail' => '<p>Festival Budaya dan Kuliner Desa Papanloe merupakan event tahunan yang bertujuan untuk melestarikan budaya lokal, mempromosikan kuliner khas, dan meningkatkan ekonomi masyarakat melalui pariwisata desa.</p><p><strong>Rangkaian acara:</strong></p><ul><li>Parade budaya dan kostum tradisional</li><li>Pameran kerajinan tangan</li><li>Bazaar kuliner khas Bugis-Makassar</li><li>Pertunjukan tari dan musik daerah</li><li>Lomba masak tradisional</li><li>Workshop kerajinan untuk wisatawan</li></ul>',
                'kategori' => 'kegiatan',
                'status' => 'aktif',
                'prioritas' => 'tinggi',
                'tanggal_mulai' => Carbon::now()->addDays(45)->setTime(8, 0),
                'tanggal_selesai' => Carbon::now()->addDays(47)->setTime(22, 0),
                'waktu_mulai' => '08:00',
                'waktu_selesai' => '22:00',
                'tempat' => 'Area Wisata Desa Papanloe',
                'alamat_lengkap' => 'Kawasan Wisata Desa Papanloe, Kec. Somba Opu, Kab. Gowa',
                'penyelenggara' => 'Pokdarwis Desa Papanloe & UMKM Lokal',
                'target_peserta' => 'Masyarakat umum, wisatawan, pecinta budaya',
                'perlu_pendaftaran' => false,
                'contact_person' => 'Ketua Pokdarwis',
                'contact_phone' => '081234567897',
                'contact_email' => 'pokdarwis@papanloe.desa.id',
                'fasilitas' => 'Panggung utama, Area parkir luas, Toilet umum, Musholla, P3K',
                'biaya' => 0,
                'catatan' => 'Acara gratis untuk umum. Mari lestarikan budaya dan dukung UMKM lokal!',
                'meta_description' => 'Festival Budaya dan Kuliner Desa Papanloe untuk melestarikan budaya lokal dan promosi wisata desa.',
                'views' => rand(300, 800),
                'is_featured' => true,
                'created_by' => $adminId,
                'updated_by' => $adminId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($agenda as $item) {
            Agenda::create($item);
        }

        $this->command->info('Agenda seeder completed successfully!');
    }
}